#### Importing the modules required

In [3]:
#importing required modules
import sys
import json
import numpy as np
import pandas
from random import shuffle

Loading the dataset

In [4]:
dataset_path = "C:/Users/dhani/OneDrive/Desktop/BTP/Project Code/datasets/dataset_100ms.json"

In [5]:
with open(dataset_path) as dataset_file:
    dataset = json.loads(dataset_file.read())

Exploratory Data Analysis

In [6]:
dataset["events"]["PAPI_L3_TCM"]["mysqld_node"]["data"]

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 2450,
 0,
 0,
 4490,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1935,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,

In [5]:
type(dataset["events"]["PAPI_L3_TCM"]["mysqld_node"]["data"])

list

In [6]:
len(dataset["events"]["PAPI_L3_TCM"])

33

### Preprocessing The Dataset

In [7]:
data = []
labels = []

In [8]:
data_TCM = []
for process_type in dataset["events"]["PAPI_L3_TCM"]:
    # print(process_type)
    # labels.append(dataset["events"]["PAPI_L3_TCM"][process_type]["label"])
    temp = dataset["events"]["PAPI_L3_TCM"][process_type]["data"]
    Sum = sum(temp)
    data_TCM.append(Sum/len(temp))
    # print(Sum)


data_TCA = []
for process_type in dataset["events"]["PAPI_L3_TCA"]:
    # print(process_type)
    # labels.append(dataset["events"]["PAPI_L3_TCM"][process_type]["label"])
    temp = dataset["events"]["PAPI_L3_TCA"][process_type]["data"]
    Sum = sum(temp)
    data_TCA.append(Sum/len(temp))
    # print(Sum)


data_INS = []
for process_type in dataset["events"]["PAPI_TOT_INS"]:
    # print(process_type)
    # labels.append(dataset["events"]["PAPI_L3_TCM"][process_type]["label"])
    temp = dataset["events"]["PAPI_TOT_INS"][process_type]["data"]
    Sum = sum(temp)
    data_INS.append(Sum/len(temp))
    # print(Sum)


In [9]:
data_TCM
data_TCA
data_INS

[152.75209380234506,
 0.0,
 12068867.458961474,
 47754980.15242881,
 38614.077051926295,
 0.0,
 29619.177554438862,
 54734.14237855947,
 40463.38358458962,
 26603.053601340034,
 144044.02680067002,
 32239.331658291456,
 696.4556113902847,
 65584.89782244556,
 47761587.70686767,
 17258079.701974865,
 961952263.7863106,
 12094026.851419032,
 446520039.63342696,
 918000625.6275862,
 4405810.385642738,
 6200075.98163606,
 0.0,
 0.0,
 62496179.83472454,
 0.0,
 62976561.32721202,
 7.300500834724541,
 227017471.2909699,
 63.785953177257525,
 1141791993.3283334,
 104230678.9699115,
 5957367.559265442]

In [10]:
for i in range(0,len(data_TCA)):
    data.append([data_TCM[i],data_TCA[i],data_INS[i]])

In [11]:
data

[[80.17755443886097, 126.25963149078727, 152.75209380234506],
 [0.0, 0.0, 0.0],
 [125757.13065326633, 722461.4556113903, 12068867.458961474],
 [487376.4070351759, 2848157.6247906196, 47754980.15242881],
 [11177.949748743718, 18822.58961474037, 38614.077051926295],
 [0.0, 0.0, 0.0],
 [3514.8525963149077, 9619.658291457286, 29619.177554438862],
 [6303.932998324958, 17431.524288107204, 54734.14237855947],
 [4760.371859296482, 12969.480737018426, 40463.38358458962],
 [3105.5159128978225, 8374.552763819096, 26603.053601340034],
 [16492.48743718593, 46283.0703517588, 144044.02680067002],
 [3783.742043551089, 10416.680067001675, 32239.331658291456],
 [113.8425460636516, 198.84757118927973, 696.4556113902847],
 [7441.006700167504, 21263.003350083753, 65584.89782244556],
 [489418.0854271357, 2832096.9128978224, 47761587.70686767],
 [173741.45601436266, 1290544.7145421903, 17258079.701974865],
 [1543.524207011686, 1670.0734557595993, 961952263.7863106],
 [101415.8263772955, 700914.1302170284, 12

In [12]:
for process_type in dataset["events"]["PAPI_L3_TCM"]:
    # print(process_type)
    labels.append(dataset["events"]["PAPI_L3_TCM"][process_type]["label"])

In [13]:
labels

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0]

### Normalising the Data

In [14]:
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

In [15]:
Data = np.array(data)
Data

array([[8.01775544e+01, 1.26259631e+02, 1.52752094e+02],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.25757131e+05, 7.22461456e+05, 1.20688675e+07],
       [4.87376407e+05, 2.84815762e+06, 4.77549802e+07],
       [1.11779497e+04, 1.88225896e+04, 3.86140771e+04],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.51485260e+03, 9.61965829e+03, 2.96191776e+04],
       [6.30393300e+03, 1.74315243e+04, 5.47341424e+04],
       [4.76037186e+03, 1.29694807e+04, 4.04633836e+04],
       [3.10551591e+03, 8.37455276e+03, 2.66030536e+04],
       [1.64924874e+04, 4.62830704e+04, 1.44044027e+05],
       [3.78374204e+03, 1.04166801e+04, 3.22393317e+04],
       [1.13842546e+02, 1.98847571e+02, 6.96455611e+02],
       [7.44100670e+03, 2.12630034e+04, 6.55848978e+04],
       [4.89418085e+05, 2.83209691e+06, 4.77615877e+07],
       [1.73741456e+05, 1.29054471e+06, 1.72580797e+07],
       [1.54352421e+03, 1.67007346e+03, 9.61952264e+08],
       [1.01415826e+05, 7.00914

In [16]:
type(Data[0])
type(Data)

numpy.ndarray

In [17]:
Scaled_data = StandardScaler().fit_transform(Data)

### Creating the Deep Learning Model

In [18]:
#importing the requied modules
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD

### Creation of the model

Model 1

In [19]:
#Splitting the Data to Training and testing Data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(np.array(Scaled_data),np.array(labels), test_size=0.33, random_state=42)

In [20]:
model1 = Sequential()
model1.add(Dense(32, activation='relu', input_dim=3))
model1.add(Dense(1, activation='sigmoid'))
model1.compile(optimizer='sgd', loss='binary_crossentropy', metrics=['binary_accuracy'])

In [21]:
model1.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                128       
                                                                 
 dense_1 (Dense)             (None, 1)                 33        
                                                                 
Total params: 161
Trainable params: 161
Non-trainable params: 0
_________________________________________________________________


In [22]:
model1.fit(X_train, np.array(y_train), validation_split=.1, epochs=1000)

Epoch 1/1000


1/1 [==============================] - 1s 1s/step - loss: 0.7649 - binary_accuracy: 0.0526 - val_loss: 0.6809 - val_binary_accuracy: 0.3333
Epoch 2/1000
1/1 [==============================] - 0s 51ms/step - loss: 0.7593 - binary_accuracy: 0.0526 - val_loss: 0.6794 - val_binary_accuracy: 0.3333
Epoch 3/1000
1/1 [==============================] - 0s 47ms/step - loss: 0.7537 - binary_accuracy: 0.0526 - val_loss: 0.6779 - val_binary_accuracy: 0.3333
Epoch 4/1000
1/1 [==============================] - 0s 45ms/step - loss: 0.7482 - binary_accuracy: 0.0526 - val_loss: 0.6764 - val_binary_accuracy: 0.3333
Epoch 5/1000
1/1 [==============================] - 0s 41ms/step - loss: 0.7428 - binary_accuracy: 0.0526 - val_loss: 0.6749 - val_binary_accuracy: 0.3333
Epoch 6/1000
1/1 [==============================] - 0s 47ms/step - loss: 0.7374 - binary_accuracy: 0.0526 - val_loss: 0.6734 - val_binary_accuracy: 0.3333
Epoch 7/1000
1/1 [==============================] - 0s 50ms/step - loss: 0.7322 - bin

In [23]:
predictions = model1.predict([np.array(X_test)])

1/1 [==============================] - 0s 109ms/step


In [2]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

In [25]:
predictions,y_test

(array([[0.04864218],
        [0.03281069],
        [0.15304047],
        [0.02794081],
        [0.02269027],
        [0.0226524 ],
        [0.8172173 ],
        [0.03053777],
        [0.02258467],
        [0.02258399],
        [0.02277996]], dtype=float32),
 array([1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0]))

In [26]:
print(np.round(predictions[6]))

[1.]


In [27]:
for i in predictions:
    i[0] = i[0]*10

for i in predictions:
    if i[0]>0.5:
        i[0]=1
    else:
        i[0]=0

In [28]:
accuracy_score(y_test, predictions)

0.7272727272727273

In [1]:
f1_score(y_test, predictions, average='weighted')

NameError: name 'f1_score' is not defined

Model 2

In [29]:
from sklearn.svm import SVC
svm_model = SVC()

In [30]:
svm_model.fit(X_train,y_train)

SVC()

In [31]:
predictions_svm = svm_model.predict(X_test)
predictions_svm

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [32]:
accuracy_score(y_test, predictions_svm)

0.7272727272727273

Model 3

In [33]:
from sklearn.ensemble import RandomForestClassifier
RF_model = RandomForestClassifier() #using Random Forest Classifier

In [34]:
RF_model.fit(X_train, y_train) 

RandomForestClassifier()

In [35]:
prediction_rf = RF_model.predict(X_test)
prediction_rf

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [36]:
accuracy_score(y_test, prediction_rf)

0.8181818181818182

Model 4

In [37]:
model2 = Sequential()
model2.add(Dense(100, activation='relu', input_dim=3))
model2.add(Dense(1, activation='sigmoid'))
model2.compile(optimizer='sgd', loss='binary_crossentropy', metrics=['binary_accuracy'])

In [38]:
model2.fit(X_train, np.array(y_train), validation_split=.1, epochs=1000)

Epoch 1/1000
1/1 [==============================] - ETA: 0s - loss: 0.7242 - binary_accuracy: 0.2632

1/1 [==============================] - 1s 1s/step - loss: 0.7242 - binary_accuracy: 0.2632 - val_loss: 0.7515 - val_binary_accuracy: 0.0000e+00
Epoch 2/1000
1/1 [==============================] - 0s 50ms/step - loss: 0.7190 - binary_accuracy: 0.2632 - val_loss: 0.7483 - val_binary_accuracy: 0.3333
Epoch 3/1000
1/1 [==============================] - 0s 33ms/step - loss: 0.7138 - binary_accuracy: 0.3158 - val_loss: 0.7451 - val_binary_accuracy: 0.3333
Epoch 4/1000
1/1 [==============================] - 0s 49ms/step - loss: 0.7087 - binary_accuracy: 0.3158 - val_loss: 0.7419 - val_binary_accuracy: 0.3333
Epoch 5/1000
1/1 [==============================] - 0s 59ms/step - loss: 0.7036 - binary_accuracy: 0.3158 - val_loss: 0.7387 - val_binary_accuracy: 0.3333
Epoch 6/1000
1/1 [==============================] - 0s 55ms/step - loss: 0.6986 - binary_accuracy: 0.3158 - val_loss: 0.7355 - val_binary_accuracy: 0.3333
Epoch 7/1000
1/1 [==============================] - 0s 47ms/step - loss: 0.6936 -

In [39]:
predictions_model2 = model2.predict([np.array(X_test)])
predictions_model2

1/1 [==============================] - 0s 115ms/step


array([[0.04644395],
       [0.02777041],
       [0.1160536 ],
       [0.0240595 ],
       [0.01992971],
       [0.01989666],
       [0.8447054 ],
       [0.02710229],
       [0.01983739],
       [0.01983678],
       [0.02001867]], dtype=float32)

In [40]:
for i in predictions_model2:
    i[0] = i[0]*10

for i in predictions_model2:
    if i[0]>0.5:
        i[0]=1
    else:
        i[0]=0

In [41]:
accuracy_score(y_test, predictions_model2)

0.7272727272727273

In [50]:
import pydot
import graphviz

In [46]:
dot = pydot.graph_from_keras(model1)
dot.write_png('model.png')

AttributeError: module 'pydot' has no attribute 'graph_from_keras'

In [47]:
import tensorflow as tf

In [51]:
tf.keras.utils.plot_model(model1, to_file='model.png')

You must install pydot (`pip install pydot`) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) for plot_model to work.


In [42]:
import pickle