In [1]:
#importing required modules
import sys
import json
import numpy
import pandas
from random import shuffle

Loading the dataset

In [2]:
dataset_path = "C:/Users/dhani/OneDrive/Desktop/BTP/Project Code/datasets/dataset_100ms.json"

In [3]:
with open(dataset_path) as dataset_file:
    dataset = json.loads(dataset_file.read())

Exploratory Data Analysis

In [4]:
len(dataset["events"]["PAPI_L3_TCM"]["mysqld_node"]["data"])

598

In [5]:
type(dataset["events"]["PAPI_L3_TCM"]["mysqld_node"]["data"])

list

In [6]:
len(dataset["events"]["PAPI_L3_TCM"])

33

### Preprocessing The Dataset

In [7]:
data = []
labels = []

In [8]:
for process_type in dataset["events"]["PAPI_L3_TCM"]:
    # print(process_type)
    labels.append(dataset["events"]["PAPI_L3_TCM"][process_type]["label"])


for process_type in dataset["events"]["PAPI_L3_TCM"]:
    # print(process_type)
    data.append(dataset["events"]["PAPI_L3_TCM"][process_type]["data"])

In [9]:
# i=0
# for process_type in dataset["events"]["PAPI_L3_TCA"]:
#     # print(process_type)
#     labels[i]+=dataset["events"]["PAPI_L3_TCA"][process_type]["label"]
#     i+=1

i=0
for process_type in dataset["events"]["PAPI_L3_TCA"]:
    # print(process_type)
    data[i]+=dataset["events"]["PAPI_L3_TCA"][process_type]["data"]
    i+=1

In [10]:
# i=0
# for process_type in dataset["events"]["PAPI_TOT_INS"]:
#     # print(process_type)
#     labels[i]+=dataset["events"]["PAPI_TOT_INS"][process_type]["label"]
#     i+=1

i=0
for process_type in dataset["events"]["PAPI_TOT_INS"]:
    # print(process_type)
    data[i]+=dataset["events"]["PAPI_TOT_INS"][process_type]["data"]
    i+=1

In [11]:
for i in data:
    print(len(i))
    # print(type(i))

1791
1791
1791
1791
1791
1791
1791
1791
1791
1791
1791
1791
1791
1791
1791
1671
1797
1797
2136
1740
1797
1797
1797
1797
1797
1797
1797
1797
1794
1794
1800
1695
1797


In [12]:
for it in data:
    while len(it)<=2136:
        it.append(0)


In [13]:
for i in data:
    print(len(i))

2137
2137
2137
2137
2137
2137
2137
2137
2137
2137
2137
2137
2137
2137
2137
2137
2137
2137
2137
2137
2137
2137
2137
2137
2137
2137
2137
2137
2137
2137
2137
2137
2137


### Normalising the Data

In [14]:
import matplotlib.pyplot as plt

In [15]:
from sklearn.preprocessing import StandardScaler

In [64]:
Data = numpy.asarray(data)

In [65]:
data
Data

array([[      0,       0,       0, ...,       0,       0,       0],
       [      0,       0,       0, ...,       0,       0,       0],
       [      0,       0,   44738, ...,       0,       0,       0],
       ...,
       [   1609, 6748271, 6459756, ...,       0,       0,       0],
       [ 785294,  798466,  831070, ...,       0,       0,       0],
       [      0, 1113416, 1156698, ...,       0,       0,       0]])

In [43]:
type(Data[0])

numpy.ndarray

In [44]:
for i in Data:
    i = numpy.asarray(i)

In [59]:
Data = StandardScaler().fit_transform(Data)

In [66]:
scaler = StandardScaler()

In [68]:
Data = scaler.fit_transform(Data)

In [114]:
len(scaler.mean_)

1

In [113]:
Data

array([[-0.23974662, -0.38005703, -0.37953522, ..., -0.1767767 ,
        -0.1767767 ,  0.        ],
       [-0.23974662, -0.38005703, -0.37953522, ..., -0.1767767 ,
        -0.1767767 ,  0.        ],
       [-0.23974662, -0.38005703, -0.34606067, ..., -0.1767767 ,
        -0.1767767 ,  0.        ],
       ...,
       [-0.23587923,  4.31318303,  4.45388209, ..., -0.1767767 ,
        -0.1767767 ,  0.        ],
       [ 1.64778409,  0.17525449,  0.24230067, ..., -0.1767767 ,
        -0.1767767 ,  0.        ],
       [-0.23974662,  0.3942937 ,  0.48594702, ..., -0.1767767 ,
        -0.1767767 ,  0.        ]])

In [21]:
# from sklearn.preprocessing import trai

### Creating the Deep Learning Model

In [22]:
#importing the requied modules
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD

Creation of the model

In [34]:
model = Sequential()
model.add(Dense(32, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='sgd', loss='binary_crossentropy', metrics=['binary_accuracy'])

In [ ]:
model.summary()

In [50]:
from sklearn.model_selection import train_test_split

In [51]:
from sklearn.svm import SVC
model = SVC()

In [52]:
model.fit(X_train,y_train)

SVC()

In [53]:
p = model.predict(X_test)

In [54]:
p

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [60]:
X_train, X_test, y_train, y_test = train_test_split(Data,numpy.array(labels), test_size=0.33, random_state=42)

In [36]:
model.fit(X_train, numpy.array(y_train), validation_split=.1, epochs=1000)

Epoch 1/1000
1/1 [==============================] - 1s 1s/step - loss: 0.3391 - binary_accuracy: 0.8947 - val_loss: 0.4758 - val_binary_accuracy: 0.6667
Epoch 2/1000
1/1 [==============================] - 0s 52ms/step - loss: 0.1974 - binary_accuracy: 1.0000 - val_loss: 0.4649 - val_binary_accuracy: 0.6667
Epoch 3/1000
1/1 [==============================] - 0s 44ms/step - loss: 0.1614 - binary_accuracy: 1.0000 - val_loss: 0.4582 - val_binary_accuracy: 0.6667
Epoch 4/1000
1/1 [==============================] - 0s 41ms/step - loss: 0.1396 - binary_accuracy: 1.0000 - val_loss: 0.4536 - val_binary_accuracy: 0.6667
Epoch 5/1000
1/1 [==============================] - 0s 37ms/step - loss: 0.1248 - binary_accuracy: 1.0000 - val_loss: 0.4503 - val_binary_accuracy: 0.6667
Epoch 6/1000
1/1 [==============================] - 0s 42ms/step - loss: 0.1137 - binary_accuracy: 1.0000 - val_loss: 0.4495 - val_binary_accuracy: 0.6667
Epoch 7/1000
1/1 [==============================] - 0s 50ms/step - loss:

In [27]:
predictions = model.predict([numpy.array(X_test)])

1/1 [==============================] - 0s 150ms/step


In [55]:
from keras.models import load_model

In [73]:
model1 = load_model("C:/Users/dhani/OneDrive/Desktop/BTP/spectre-real-time-detection/spectre_real_time_detection/model.h5")

In [74]:
model1.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 32)                128       
                                                                 
 dense_2 (Dense)             (None, 1)                 33        
                                                                 
Total params: 161
Trainable params: 161
Non-trainable params: 0
_________________________________________________________________


In [77]:
len(X_test[0])

2137

In [153]:
t1 = dataset["events"]["PAPI_L3_TCA"]["mysqld_safe"]["data"]
t2 = dataset["events"]["PAPI_L3_TCM"]["mysqld_safe"]["data"]
t3 = dataset["events"]["PAPI_TOT_INS"]["mysqld_safe"]["data"]
t_label = dataset["events"]["PAPI_TOT_INS"]["mysqld_safe"]["label"]

In [154]:
t_label

0

In [155]:
X_t1 = 0
for i in t1:
    X_t1+=i

X_t2 = 0
for i in t2:
    X_t2+=i

X_t3 = 0
for i in t3:
    X_t3+=i

X_t1 = X_t1/len(t1)
X_t2 = X_t2/len(t2)
X_t3 = X_t3/len(t3)

In [156]:
X_t1

0.0

In [157]:
test_input = [X_t1,X_t2,X_t3]
TI = numpy.array(test_input)
TI

array([0., 0., 0.])

In [ ]:
TI = scaler.fit_transform(TI)
TI

In [116]:
import tensorflow as tf

In [158]:
tensor1 = tf.convert_to_tensor([TI])
tensor1

<tf.Tensor: shape=(1, 3), dtype=float64, numpy=array([[0., 0., 0.]])>

In [112]:
scaler.mean_


array([7.40148683e-17])

In [159]:
test_pred = model1.predict(tensor1)
test_pred

1/1 [==============================] - 0s 30ms/step


array([[5.489177e-14]], dtype=float32)

In [144]:
from sklearn.metrics import accuracy_score